services:
  backend:
    image: botonetics/tracker-sim-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app

  frontend:
    image: botonetics/tracker-sim-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    working_dir: /app

networks:
  default:
    driver: bridge